version: "3"

services:
  reactad:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/reactAd
    tty: true
    ports:
      - 5173:5173
    container_name: reactad
